version: '3.3'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: customuser
      POSTGRES_PASSWORD: custompass
      POSTGRES_DB: bankdb
    ports:
      - "5433:5432"
    container_name: springContainer