version: '3.3'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg123456
    ports:
      - "5432:5432"
    container_name: springContainer
