spring:
  application:
    name: SpringWeb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        javax.persistence.validation.mode: auto
  profiles:
    active: local  # ?? ????????????? - local

server:
  port: 9000  # ???? ??? ????????

---
spring:
  config:
    activate:
      on-profile: local  # H2 ??? ?????????? ???????
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE  # ?????????????? in-memory ????
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always  # ??????????? ?????????? V2__insert_sample_data.sql
  h2:
    console:
      enabled: true  # ?????????? H2 Console
      path: /h2-console  # ?????? ?? ??????????? ??????????

---
spring:
  config:
    activate:
      on-profile: prod  # PostgreSQL ??? ??????????
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: pg123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
